# Generated by Django 3.2.12 on 2022-02-18 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('searched_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result', models.TextField(blank=True)),
                ('searched_by', models.ForeignKey(db_column='Searched_by', default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
