# Generated by Django 3.2.12 on 2022-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
