# Generated by Django 3.2.12 on 2022-02-21 07:01

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchapp', '0002_search_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched_by',
            field=models.ForeignKey(db_column='Searched_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Searchhistory',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('searched_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('counter', models.IntegerField()),
                ('searchresult', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8), size=8)),
                ('searched_by', models.ForeignKey(db_column='Searched_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
