# Generated by Django 3.2.12 on 2022-02-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_merge_0003_auto_20220221_1301_0003_auto_20220221_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searchhistory',
        ),
    ]
